name = "theoaddo-com"
pages_build_output_dir = "."
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "THEO_OS_DB"
database_name = "theo_os_db"
database_id = "2501e619-c84d-44ab-acac-c2564fbad1aa"

[[kv_namespaces]]
binding = "THEO_OS_KV"
id = "f5de0039149c4717941a9e2e75bfd7f2"

[triggers]
crons = ["0 6 * * *", "0 10 * * 0"]

[vars]
ENVIRONMENT = "production"
